version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "monthly"
  reviewers: ["mehm8128", "nokhnaton", "ras0q", "zer0-star"]
  open-pull-requests-limit: 10
  versioning-strategy: "increase"
  groups:
    npm-prod-deps:
      dependency-type: "production"
      update-types:
      - "minor"
      - "patch"
    npm-dev-deps:
      dependency-type: "development"
      update-types:
      - "minor"
      - "patch"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  reviewers: ["mehm8128", "nokhnaton", "ras0q", "zer0-star"]
