version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:latest-node
    working_directory: ~/work_dir
    steps:
      - checkout
      - run:
          name: npm ci
          command: |
            npm ci
      - run:
          name: build
          command: |
            npm run build
      - deploy:
          name: Check diff, commit and push
          command: |
            git diff --unified=0 > ./diff.txt
            if [ -s './diff.txt' ]; then
              rm ./diff.txt

              TRAQ_VERSION=$(curl -sS https://api.github.com/repos/traPtitech/traQ/tags | jq '.[0].name' | sed -n s/[\"v]//pg)
              echo "TRAQ ${TRAQ_VERSION}"

              VERSION=$(cat ./package.json | jq .version | sed -n s/\"//pg | sed -n s/-/./p)
              echo "PACKAGE ${VERSION}"
              VERSION_ARR=($(echo $VERSION | tr -s '.' ' '))
              VERSION_SHORT=${VERSION_ARR[0]}.${VERSION_ARR[1]}.${VERSION_ARR[2]}
              echo "PACKAGE SHORT ${VERSION_SHORT}"

              if [ $TRAQ_VERSION = $VERSION_SHORT ]; then
                let VERSION_ARR[3]++ 1
                NEW_VERSION="${VERSION_ARR[0]}.${VERSION_ARR[1]}.${VERSION_ARR[2]}-${VERSION_ARR[3]}"
              else
                NEW_VERSION="${TRAQ_VERSION}-0"
              fi
              echo "PACKAGE NEW ${NEW_VERSION}"

              npm --no-git-tag-version version $NEW_VERSION

              git config user.name "sapphi-red+circleci"
              git config user.email "sapphi-red+circleci@users.noreply.github.com"
              
              git add .
              git commit -m "CI: build $NEW_VERSION" -m "[ci skip]"
              git push origin master
              git tag $NEW_VERSION
              git push origin $NEW_VERSION
            else
              echo 'There are no difference.'
            fi
