name: check npm ci & build
on: [push, pull_request]
jobs:
  check:
    name: check npm ci & build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: check npm ci
        run: npm ci
      - name: check npm build
        run: npm run build
