name: automatic update
on:
  repository_dispatch:
  push:
    branches:
      - master
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '13'
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'
      - name: npm ci
        run: npm ci
      - name: build
        run: npm run build
      - name: Check diff, commit and push
        run: |
          git diff --unified=0 > ./diff.txt
          if [ -s './diff.txt' ]; then
            rm ./diff.txt

            #TRAQ_VERSION=$(curl -sS https://api.github.com/repos/traPtitech/traQ/tags | jq '.[0].name' | sed -n s/[\"v]//pg)
            TRAQ_VERSION=3.0.0
            echo "TRAQ ${TRAQ_VERSION}"

            VERSION=$(cat ./package.json | jq .version | sed -n s/\"//pg | sed -n s/-/./p)
            echo "PACKAGE ${VERSION}"
            VERSION_ARR=($(echo $VERSION | tr -s '.' ' '))
            VERSION_SHORT=${VERSION_ARR[0]}.${VERSION_ARR[1]}.${VERSION_ARR[2]}
            echo "PACKAGE SHORT ${VERSION_SHORT}"

            if [ $TRAQ_VERSION = $VERSION_SHORT ]; then
              let VERSION_ARR[3]++ 1
              NEW_VERSION="${VERSION_ARR[0]}.${VERSION_ARR[1]}.${VERSION_ARR[2]}-${VERSION_ARR[3]}"
            else
              NEW_VERSION="${TRAQ_VERSION}-0"
            fi
            echo "PACKAGE NEW ${NEW_VERSION}"

            npm version $NEW_VERSION
            npm publish --access public

            git config user.name "sapphi-red+circleci"
            git config user.email "sapphi-red+circleci@users.noreply.github.com"

            git add .
            git commit -m "CI: build $NEW_VERSION" -m "[ci skip]"
            git push origin master
            git push origin $NEW_VERSION
          else
            echo 'There are no difference.'
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
